[[about_oce]]
<<<<<<< HEAD
= About {oce}
{product-author}
{product-version}
:oce: OpenShift Container Engine
=======
= About OpenShift Container Engine
{product-author}
{product-version}
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:


<<<<<<< HEAD
Red Hat {oce} is a new product offering from Red Hat
that lets you use {product-title} as a production platform for launching
containers. You download and install {oce} in the same way as {product-title},
but {oce} offers a subset of the features that {product-title} does.

[[about_oce_similarities_and_differences]]
== Similarities and differences
You can see the similarities and differences between {oce}
and {product-title} in the following table:

.Product comparison for {oce} and {product-title}
|===
2+| |{oce} |{product-title}
=======
Red Hat OpenShift Container Engine is a new product offering from Red Hat
that lets you use {product-title} as a production platform for launching
containers. You download and install OpenShift Container Engine in the same way as {product-title},
but OpenShift Container Engine offers a subset of the features that {product-title} does.

== Similarities and Differences
Specifically, the similarities and difference between Red Hat OpenShift Container Engine and OpenShift Container Platform
are the following:

.Product comparison for OpenShift Container Engine and {product-title}
|===
2+| |Engine |Platform
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

2+h|Core Kubernetes and container orchestration
| X
| X

<<<<<<< HEAD
2+h|Enterprise-ready configurations
| X
| X

2+h|Standard infrastructure services
| X
| X

2+h|Core user experience
| X
| X

2+h|Maintained and curated content
| X
| X

2+h|OpenShift Container Storage compatible
| X
| X

2+h|Red Hat Middleware compatible
| X
| X

2+h|Serverless Cloud Functions compatible
| X
| X

2+h|Quay integration compatible
| X
| X

2+h|Container Native Virtualization for virtual machines compatible
=======
2+h|Enterprise Ready Configurations
| X
| X

2+h|Standard Infrastructure Services
| X
| X

2+h|Core User Experience
| X
| X

2+h|Maintained and Curated Content
| X
| X

2+h|OpenShift Container Storage Compatible
| X
| X

2+h|Red Hat Middleware Compatible
| X
| X

2+h|Cloud Functions Compatible
| X
| X

2+h|Quay Integration Compatible
| X
| X

2+h|CNV VM Virtualization Compatible
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
| X
| X

2+h|Advanced cluster management
|
| X

<<<<<<< HEAD
2+h|Advanced networking
|
| X

2+h|Developer experience
=======
2+h|Advanced Networking
|
| X

2+h|Developer Experience
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
|
| X

|===

<<<<<<< HEAD
[[about_oce_core_kubernetes_and_container_orchestration]]
=== Core Kubernetes and container orchestration
{oce} offers full access to an enterprise-ready Kubernetes
environment that is easy to install and offers an extensive compatibility test
matrix with many of the that software elements that you might use in your data
center.

{oce} offers the same service level agreements, bug fixes, and common
vulnerabilities and errors protection as {product-title}. {oce} includes a
Red Hat Enterprise Linux Virtual Datacenter and Red Hat CoreOS entitlement that
allows you to use an integrated Linux operating system with container runtime
from the same provider.

{oce} is compatible with Windows Containers from Microsoft.

[[about_oce_enterprise_ready_configurations]]
=== Enterprise-ready configurations
{oce} uses the same security options and default settings as the {product-title}.
Default security context constraints, pod security policies, best practice
network and storage settings, service account configuration, SELinux integration,
HAproxy edge routing configuration, and all other standard protections that
{product-title} offers are available in {oce}. {oce} offers full access to the
integrated monitoring solution that {product-title} uses, which is based on
Prometheus and offers deep coverage and alerting for common Kubernetes issues.

{oce} uses the same installation and upgrade automation as {product-title}.

[[about_oce_standard_infrastructure_services]]
=== Standard infrastructure services
With an {oce} subscription, you receive support for all storage plug-ins that
{product-title} supports.

In terms of networking, {oce} offers full and
supported access to the Kubernetes Container Network Interface (CNI) and
therefore allows you to use any third-party SDN that supports {product-title}.
It also allows you to use the included Open vSwitch to establish a flat,
non-project (Kubernetes namespace) segmented network for the Kubernetes cluster.
{oce} allows customers to use a Kubernetes Network Policy to create
microsegmentation between deployed application services on the cluster.

You can also use the route API objects that are found in {product-title},
including its sophisticated integration with the HAproxy edge routing layer.

[[about_oce_core_user_experience]]
=== Core user experience
{oce} users have full access to Kubernetes Operators, pod deployment strategies,
Helm, and {product-title} templates. {oce} users can use both the `oc` and
`kubectl` command line interfaces. {oce} also offers an administrator web-based
console that shows all aspects of the deployed container services and offers a
container-as-a service experience. {oce} grants access to the Operator Life
Cycle Manager that helps you control access to content on the cluster and life
cycle operator-enabled services that you use. With an {oce} subscription, you
receive access to the Kubernetes namespace, the OpenShift Project API object,
and both cluster-level and tenant-level Prometheus monitoring metrics and events.

=== Maintained and curated content
With an {oce} subscription, you receive access to the {product-title} entitled
content from the Red Hat Container Catalog and Red Hat Connect ISV marketplace.
You can access all maintained and curated content that the {product-title}
eco-system offers either for free, such as the Red Hat Software Collections,
or through additional purchases. The Kubernetes service broker, service catalog,
and all {product-title} service broker offerings are supported with an
{oce} subscription.

=== OpenShift Container Storage compatible
{oce} is compatible and supported with OpenShift Container Storage.

=== Red Hat Middleware compatible
{oce} is compatible and supported with Red Hat Middleware product solutions.

=== Serverless Cloud Functions compatible
{oce} is compatible and supported with future Red Hat Cloud Functions products,
such as function based and serverless container services.

=== Quay Integration compatible
{oce} is compatible and supported with Red Hat Quay.

CNV VM Virtualization Compatible
{oce} is compatible and supported with Red Hat product offerings derived from
the kubevirt.io open source project.

=== Advanced cluster management
A {oce} subscription does not offer a cluster-wide log aggregation
solution or support ElasticSearch, Fluentd, Kibana based logging solutions.
Similarly the chargeback features found in {product-title} and Red Hat Service
Mesh capabilities derived from the open source Istio.io and kiali.io projects
that offers OpenTracing observability for containerized services on
{product-title} are not supported.

=== Advanced networking
The standard networking solutions in {product-title} are not supported with an
{oce} subscription. {product-title}’s Kubernetes CNI plug-in for automation of
multi-tenant network segmentation between {product-title} projects is not
entitled for use with {oce}. {product-title} offers more granular control of the
source IP addresses that are used by application services on the cluster.
Those egress IP address controls are not entitled for use with {oce}.
{product-title} offers ingress routing to on cluster services that use
non-standard ports when no public cloud provider is in use via the VIP pods
found in {product-title}. That ingress solution is not supported in {oce}.
{oce} users are supported for the Kubernetes ingress control object, which
offers integrations with public cloud providers. Red Hat Service Mesh, which is
derived from the istio.io open source project, is not supported in {oce}.

=== Developer experience
With {oce}, the following capabilities are not supported:

* The developer experience utilities and tools.
* {product-title}’s pipeline feature that integrates a streamlined,
Kubernetes-enabled Jenkins experience in the user’s project space.
* The {product-title}’s source-to-image feature, which allows you to easily
deploy source code, dockerfiles, or container images across the cluster.
* Build strategies, builder pods, or imagestreams for end user container
deployments.
* The `odo` developer command line.
* The developer persona in the {product-title} web console.

=== Feature summary

The following table is a summary of the feature availability in {oce} and
{product-title}.

.Features in {oce} and {product-title}
|===
2+| |{oce} |{product-title}
=======
== Feature Explanations
We will now offer a deeper explanation of the categories in order to more fully explain the feature
entitlement of OpenShift Container Engine.

=== Core Kubernetes and Container Orchestration
OpenShift Container Engine offers full access to an enterprise ready Kubernetes.  You will receive a packaged, easy to install Kubernetes
that has undergone an extensive compatibility test matrix with many of the software elements you will find in your datacenter.
Engine offers the same service level agreements, bug fixes, and CVE protection as OpenShift Container Platform.
Engine includes a Red Hat Enterprise Linux Virtual Datacenter and Red Hat CoreOS entitlement that allows you to use an integrated Linux operating system with container runtime all from the same provider.  OpenShift Container Engine is compatible with Windows Containers from Microsoft.

=== Enterprise Ready Configurations
OpenShift Container Engine comes with the same security options and default settings as the OpenShift Container Platform.
Default security context constraints, pod security policies, best practice network and storage settings, service account configuration, SELinux integration, HAproxy edge routing configuration, and all other out of the box protections OpenShift Container Platform offers are available in OpenShift Container Engine.  Engine offers full access to our integrated monitoring solution, based on Prometheus, that offer deep coverage and alerting of common Kubernetes’ issues.  Red Hat entitles OpenShift Container Engine to the same installation and upgrade automations as OpenShift Container Platform.

=== Standard Infrastructure Services
With an OpenShift Container Engine Subscription users receive support for  all storage plugins found in OpenShift Container Platform.  In terms of networking, OpenShift Container Engine offers full and supported access to the Kubernetes Container Network Interface (CNI) and therefore allows you to leverage any 3rd party SDN that supports OpenShift Container Platform.  It also allows for the use of the included OVS to establish a flat, non-project (Kubernetes namespace) segmented network for the Kubernetes cluster.  Engine allows customers to use Kubernetes Network Policy to create microsegmentation between deployed application services on the cluster.  OpenShift Container Engine also grants full use of the route API object found in OpenShift including its sophisticated integration with the HAproxy edge routing layer.
Core User Experience
A user of the OpenShift Container Engine will be most interested in experiencing a native Kubernetes experience.  They have full access to Kubernetes Operators, pod deployment strategies, Helm, and OpenShift templates.  Engine users will leverage the oc and kubectl command lines.  Engine also offers an administrator web based console that shows all aspects of their deployed container services and is more in line with a container as a service experience.  OpenShift Container Engine grants access to the Operator Life Cycle Manager that helps cluster administrators and users control access to content on the cluster as well as life cycle operator enabled services that might be in use. With an  Engine Subscription users receive  access to both the Kubernetes namespace and the OpenShift Project API object that layers on top as well as both cluster level and tenant level Prometheus monitoring metrics and events.

=== Maintained and Curated Content
If you purchase an OpenShift Container Engine Subscription you receive access to  the OpenShift Container Platform entitled content from the Red Hat Container Catalog and Red Hat Connect ISV marketplace.  With an Engine  Subscription you receive access  to all maintained and curated content that the OpenShift eco-system offers either for free, such as the Red Hat Software Collections, or through additional purchases.  The Kubernetes service broker, service catalog, and all OpenShift Container Platform service broker offerings are supported with an OpenShift Container Platform Engine Subscription.

=== OpenShift Container Storage Compatible
OpenShift Container Engine is compatible and supported with OpenShift Container Storage should users want to buy this Red Hat product addon.

=== Red Hat Middleware Compatible
OpenShift Container Engine is compatible and supported with Red Hat Middleware product solutions should users want to buy these Red Hat product addons.

=== Cloud Functions Compatible
OpenShift Container Engine is compatible and supported with future Red Hat Cloud Functions deliverables should users want to experience function based or serverless container services.

=== Quay Integration Compatible
OpenShift Container Engine is compatible and supported with Red Hat Quay should users want to buy this Red Hat product solution.
CNV VM Virtualization Compatible
OpenShift Container Engine is compatible and supported with Red Hat product offerings derived from the kubevirt.io open source project should users want to buy such solutions.

=== Multi-Cluster Federation
OpenShift Container Engine can be used in multi-cluster deployment configuration to the same extent OpenShift Container Platform.  Consolidated views of clusters and the use of Kubernetes technologies to offer an agnostic layer across public and on premises clouds is allowed with Engine.

=== Advanced Management
A OpenShift Container Engine Subscription does not come with support for  cluster wide log aggregation solution or for ElasticSearch, Fluentd, Kibana based logging solution.  Similarly the chargeback features found in OpenShift Container Platform  and  Red Hat Service Mesh capabilities derived from the open source Istio.io and kiali.io project that offers OpenTracing observability for containerized services on the platform are not supported.

=== Advanced Networking
The networking solutions that come out of the box with OpenShift Container Platform are not supported with an OCPE subscription .  OpenShift’s Kubernetes CNI plugin for automation of multi-tenant network segmentation between OpenShift projects is not entitled for use with Engine.  OpenShift Container Platform offers more granular control of source IPaddress used by application services on the cluster.  Those egress IPaddress controls are not entitled for use with Engine.  OpenShift Container Platform offers ingress routing to on cluster services that use non-standard ports when no public cloud provider is in use via the VIP pods found in the OpenShift product.  That ingress solution is not supported in Engine.  Engine users are supported for  the Kubernetes ingress control object which offers integrations with public cloud providers to solve this use case.  Red Hat Service Mesh that is derived from the istio.io open source project is not supported in the OpenShift Container Engine offering.

=== Developer Experience
With an OpenShift Container Engine the following capabilities are not supported: developer experience utilities and tools,  OpenShift’s pipeline feature that integrates a streamlined, Kubernetes enabled Jenkins experience in the user’s project space,  the OpenShift Container Platform’s source to image feature that allows end users to easily deploy source code, dockerfiles, or container images across the cluster in a manner that automates the segmentation between gold standard container images and line of business code additions, while automating and ability for the cluster to autonomously update the deployed application should either layer change,  build strategies, builder pods, or imagestreams for end user container deployments, or the odo developer command line or the developer persona in the OpenShift web console.

== Feature Summary

The following table is a summary of the above explanations to help provide a more clarity around what features are supported for use in OpenShift Container Engine.

.Features in OpenShift Container Engine and {product-title}
|===
2+| |Engine |Platform
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

2+h|Core Kubernetes and container orchestration
h| X
h| X

.3+|
| Enterprise-class Kubernetes
| X
| X

| Red Hat Enterprise Linux for Virtual Datacenters and Red Hat CoreOS
| X
| X

| Windows containers compatible
| X
| X

2+h|Enterprise-ready configurations
h| X
h| X

.3+|
| Complete life-cycle automation of platform
| X
| X


| Management, monitoring, alerting, and remedy through Prometheus
| X
| X


| Enterprise-ready security
| X
| X

2+h|Standard infrastructure services
h| X
h| X

.3+|
| Edge routing
| X
| X


| Flat networking
| X
| X


| Kubernetes storage plug-ins
| X
| X

2+h|Core user experience
h| X
h| X

.6+|
| Application deployments, deployment configuration, templates, and Operators
| X
| X

| Administrator console
| X
| X

| Operator life cycle management
| X
| X

| kubectl command line
| X
| X

| Developer projects
| X
| X

| Prometheus metrics
| X
| X

2+h|Maintained and curated content
h| X
h| X

.3+|
| Red Hat Container Catalog access
| X
| X

| Independent Software Vendor and partner Operator access
| X
| X

| Service Catalog and Brokers for cloud content
| X
| X

2+h|Red Hat add-ons
h|
h| X

.6+|
<<<<<<< HEAD
| OpenShift Container Storage compatible
| X
| X

| Red Hat Middleware compatible
| X
| X

| Serverless Cloud Functions compatible
| X
| X

| Istio runtime launchers compatible
|
| X

| Quay integration compatible
| X
| X

| Container Native Virtualization for virtual machines compatible
=======
| OpenShift Container Storage access
| X
| X

| Red Hat Middleware access
| X
| X

| Serverless cloud functions
| X
| X

| Istio runtime launchers
|
| X

| Quay integration
| X
| X

| Container Native Virtualization for virtual machines
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
| X
| X

2+h|Advanced cluster management
h|
h| X

.3+|
| Logging
|
| X

| Chargeback
|
| X

| Kiali (Jaeger and OpenTracing)
|
| X

2+h|Advanced networking
h|
h| X

.4+|
| Egress per pod or namespace
|
| X

| Ingress for non-standard ports
|
| X

| Multi-tenant SDN
|
| X

| Red Hat Service Mesh (Istio)
|
| X

2+h|Developer experience
h|
h| X

.4+|
| Integrated CI/CD pipelines
|
| X

| Source-to-Image Container factory
|
| X

| odo command line
|
| X

| Developer console
|
| X

|===


== Subscription Limitations

<<<<<<< HEAD
{oce} is a subscription offering that provides {product-title} with a limited set
of supported features at a lower list price. {oce} and {product-title} are the
same product and, therefore, all software and features are delivered in both.
There is only one download, {product-title}. {oce} uses the {product-title}
documentation and support services and bug errata for this reason.
=======
OpenShift Container Engine is a subscription offering that provides OpenShift Container Platform but with a limited set of
supported features at a lower list price. OpenShift Container Engine and OpenShift Container Platform are the same product and
therefore all software and features are delivered in both.
There is only one download, OpenShift Container Platform. Engine uses the OpenShift Container Platform documentation and support services
and bug errata for this reason.
If you purchase the OpenShift Container Platform Engine Subscription you need to understand that support for all the features are limited as
 set forth above.
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
