<<<<<<< HEAD
// Module included in the following assemblies:
//
// * cnv_install/cnv_install.adoc

[[uninstall_cnv]]
= Uninstalling {ProductName}
=======
[[uninstall_cnv]]
=== Uninstalling {ProductName}
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

You can uninstall {ProductName} with the same `ansible-playbook` command you
used for deployment if you change the `apb_action` parameter value to
`deprovision`.

This procedure uninstalls the following components:

* {ProductName} core components (KubeVirt)
* Containerized data importer (CDI) controller
* Multus, Open vSwitch (OVS), and SR-IOV container network interface plug-ins
* {ProductName} web console

.Prerequisites

* {ProductName} 1.4

.Procedure

. Log into the {product-title} cluster as an admin user:
+
----
$ oc login -u system:admin
----

. Change directories to `/usr/share/ansible/kubevirt-ansible`:
+
----
$ cd /usr/share/ansible/kubevirt-ansible
----

. Uninstall {ProductName}:
+
----
$ ansible-playbook -i <inventory_file> -e @vars/cnv.yml playbooks/kubevirt.yml \
-e apb_action=deprovision
----

. Remove {ProductName} packages:
+
----
$ yum remove kubevirt-ansible kubevirt-virtctl
----

. Disable the {ProductName} repository:
+
----
$ subscription-manager repos --disable=rhel-7-server-cnv-1.4-tech-preview-rpms
----

. To verify the uninstallation, check to ensure that no KubeVirt pods remain:
+
----
$ oc get pods --all-namespaces
<<<<<<< HEAD
----
=======
----
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
