// Module included in the following assemblies:
//
// * cnv_users_guide/cnv_users_guide.adoc

[[cnv-editing-template-yaml-web]]
<<<<<<< HEAD
= Editing the YAML of a virtual machine template
=======
== Editing the YAML of a virtual machine template
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

You can edit the YAML configuration of a virtual machine template directly within the web console. 

Not all parameters can be updated. If you edit values that cannot be changed and click *Save*, an error message shows, indicating the parameter that was not able to be updated.

[NOTE]
====
Navigating away from the YAML screen while editing cancels any changes to the configuration you have made. 
====

.Procedure

. Click *Workloads* -> *Virtual Machine Template* from the side menu.
. Select a template.
. Click the *YAML* tab to display the editable configuration. 
.. (Optional) You can click *Download* to download the YAML file locally in its current state.
. Edit the file and click *Save*. 

A confirmation message shows the modification has been successful, including the updated version number for the object. 

