// Module included in the following assemblies:
//
// * cnv_users_guide/cnv_users_guide.adoc

[[cnv-restart-vm-web]]
<<<<<<< HEAD
= Restarting a virtual machine
=======
== Restarting a virtual machine
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

A running virtual machines can be xref:cnv-vm-actions-web[restarted] using the &#8942; button of each virtual machine in the *Workloads* -> *Virtual Machines* list. 

These same control operations can be done using the xref:cnv-vm-actions-web[*Actions* control] of the *Virtual Machine Details* screen.

[IMPORTANT]
====
Do not restart a virtual machine while it has a status of *Importing*. This will result in an error for the virtual machine and is a xref:../cnv_release_notes/cnv_release_notes.adoc#RN_known_issues[known issue]. 
====

.Procedure

. Click *Workloads* -> *Virtual Machine* from the side menu.
. Click the &#8942; button of the virtual machine and select *Restart Virtual Machine*.
.. Alternatively, click the virtual machine name to open the *Virtual Machine Details* screen and click *Actions* and select *Restart Virtual Machine*. 
. In the confirmation pop-up window, click *Restart* to restart the virtual machine.

