// Module included in the following assemblies:
//
<<<<<<< HEAD
// * operators/operators-appendices.adoc
=======
// * operators/osdk-getting-started.adoc
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

[id='operator-project-scaffolding-layout_{context}']
= Operator project scaffolding layout

<<<<<<< HEAD
The `operator-sdk` CLI generates a number of packages for each Operator project.
The following sections describes a basic rundown of each generated file and
directory.

== Go-based projects

Go-based Operator projects (the default type) generated using the `operator-sdk new`
command contain the following directories and files:
=======
After creating a new Operator project using the `operator-sdk new` command, the
project directory has numerous generated folders and files. The following table
provides a basic overview of each generated file and directory.
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5

[options="header",cols="1,2"]
|===

|File/Folders |Purpose

<<<<<<< HEAD
|`cmd/`
|Contains `manager/main.go` file, which is the main program of the Operator. This
instantiates a new manager which registers all custom resource definitions under
`pkg/apis/` and starts all controllers under `pkg/controllers/`.

|`pkg/apis/`
|Contains the directory tree that defines the APIs of the Custom Resource
Definitions (CRDs). Users are expected to edit the
`pkg/apis/<group>/<version>/<kind>_types.go` files to define the API for each
resource type and import these packages in their controllers to watch for these
resource types.

|`pkg/controller`
|This `pkg` contains the controller implementations. Users are expected to edit
the `pkg/controller/<kind>/<kind>_controller.go` files to define the
controller's reconcile logic for handling a resource type of the specified
`kind`.

|`build/`
|Contains the `Dockerfile` and build scripts used to build the Operator.

|`deploy/`
|Contains various YAML manifests for registering CRDs, setting up RBAC,
and deploying the Operator as a Deployment.

a|`Gopkg.toml` +
`Gopkg.lock`
|The link:https://github.com/golang/dep[Go Dep] manifests that describe the
external dependencies of this Operator.

|`vendor/`
|The golang link:https://golang.org/cmd/go/#hdr-Vendor_Directories[vendor] folder
that contains the local copies of the external dependencies that satisfy the
imports of this project. link:https://github.com/golang/dep[Go Dep] manages the
vendor directly.

|===

== Helm-based projects

Helm-based Operator projects generated using the `operator-sdk new --type helm`
command contain the following directories and files:

[options="header",cols="1,2"]
|===

|File/Folders |Purpose

|`deploy/`
|Contains various YAML manifests for registering CRDs, setting up RBAC,
and deploying the Operator as a Deployment.

|`helm-charts/<kind>`
|Contains a Helm chart initialized using the equivalent of the
link:https://docs.helm.sh/helm/#helm-create[`helm create`] command.

|`build/`
|Contains the `Dockerfile` and build scripts used to build the Operator.

|`watches.yaml`
|Contains `Group`, `Version`, `Kind`, and Helm chart location.

=======
a|*_Gopkg.toml_* +
*_Gopkg.lock_*

|The link:https://github.com/golang/dep[Go Dep] manifests that describe the
external dependencies of this Operator.

|*_cmd/_*
|Contains the *_main.go_* file, which is the entry point to initialize and start
this Operator using the Operator SDK APIs.

|*_config/_*
|Contains metadata about state of this project such as `projectName`, `kind`,
`apiVersion`, and so forth. The `operator-sdk` commands use this metadata to
perform actions that require knowing the state.

|*_deploy/_*
|Contains a generic set of Kubernetes manifests for deploying this Operator on a
Kubernetes cluster.

|*_pkg/apis/_*
|Contains the directory tree that defines the APIs and types of Custom Resource
Definitions (CRDs). These files allow the SDK to do code generation for CRD
types and register the schemes for all types in order to correctly decode Custom
Resource (CR) objects.

|*_pkg/stub/_*
|Contains the *_handler.go_* file, which is the place for a user to write all the
operating business logic.

|*_tmp/_*
|Contains scripts that the Operator SDK uses for build and code generation.

|*_vendor/_*
|The golang link:https://golang.org/cmd/go/#hdr-Vendor_Directories[vendor] folder
that contains the local copies of the external dependencies that satisfy the
imports of this project. link:https://github.com/golang/dep[Go Dep] manages the
vendor directly.

|*_version/_*
|Contains the version for the Operator project.
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
|===
