language: python
python: 
 - 2.7

cache: pip

sudo: required

before_install:
 - sudo gem install asciidoctor -v 1.5.4
 - sudo gem install asciidoctor-diagram -v 1.5.4

install:
 - pip install pyyaml
 - pip install aura.tar.gz

script:
 - python build.py --distro openshift-enterprise --product "OpenShift Container Platform" --version 3 --no-upstream-fetch
<<<<<<< HEAD
 - if [ "$TRAVIS_BRANCH" == "enterprise-3.11" ]; then python build.py --distro openshift-online --product "OpenShift Container Platform" --version 3 --no-upstream-fetch; fi
 - if [ "$TRAVIS_BRANCH" == "enterprise-3.11" ]; then python build.py --distro openshift-dedicated --product "OpenShift Container Platform" --version 3 --no-upstream-fetch; fi
=======
 - if [ "$TRAVIS_BRANCH" == "enterprise-3.9" ] || [ "$TRAVIS_BRANCH" == "enterprise-3.10" ]; then python build.py --distro openshift-online --product "OpenShift Container Platform" --version 3 --no-upstream-fetch; fi
 - if [ "$TRAVIS_BRANCH" == "enterprise-3.7" ] || [ "$TRAVIS_BRANCH" == "enterprise-3.9" ] || [ "$TRAVIS_BRANCH" == "enterprise-3.10" ]; then python build.py --distro openshift-dedicated --product "OpenShift Container Platform" --version 3 --no-upstream-fetch; fi
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
 - python makeBuild.py

after_success:
 - bash autopreview.sh
<<<<<<< HEAD

after_failure:
 - bash autocomment.sh
=======
>>>>>>> 6bcfc60496ce2d67bb2988b30404317813a382f5
